In [40]:
import pandas as pd

In [41]:
#Reading the excel file in Pandas
df_angleBar = pd.read_excel('./Resources/AngleBar.xlsx')
df_angleBar

    Thickness Size(mm)  BA304  BA316  Weight(kg/m)
0           3    20x20   True   True          0.90
1           3    25x25   True   True          1.15
2           3    30x30   True   True          1.40
3           3    40x40   True   True          1.85
4           3    50x50   True   True          2.45
5           5    25x25   True   True          1.80
6           5    30x30  False   True          2.20
7           5    40x40   True   True          3.00
8           5    50x50   True   True          3.80
9           6    25x25  False   True          2.20
10          6    30x30  False   True          2.90
11          6    40x40   True   True          3.55
12          6    50x50   True   True          4.50
13          6    65x65   True   True          5.95
14          6    75x75   True   True          7.00
15          6  100x100   True   True          9.90
16          8    50x50  False   True          6.00
17          8    65x65  False   True          7.87
18          8    75x75  False   True          9.30
19         10    50x50  False   True          7.50
20         10    75x75   True   True         11.20
21         10  100x100   True   True         16.20
22         10  150x150  False   True         23.67
23         12  100x100  False   True         17.67

### For loop with an if statement to generate a new Index based on column name 'BA304', 'Thickness' and 'Size'.
### Then creating a new spreadsheet with the new Index and category "Angle_Bar".

In [42]:
BA304_index = []

for index, row in df_angleBar.iterrows():
    if row['BA304'] and row['Thickness'] and row['Size(mm)']:
        BA304_index.append(f"BA304_{row['Thickness']}_{row['Size(mm)']}")
    else:
        BA304_index.append(None)

df_angleBar['NewIndex'] = BA304_index
df_304 = df_angleBar[['NewIndex','Thickness','Size(mm)','Weight(kg/m)']]
df_304 = df_304.dropna().set_index('NewIndex')#Dropping null values and inserting the new index.
df_304['Category'] = 'Angle_Bar' #Adding the category "Angle_Bar to the table".
df_304.to_excel('./Resources/angleBar304Index.xlsx')

In [43]:
#This is the result of the new 304 index Angle_Bar table.
df_304

                  Thickness Size(mm)  Weight(kg/m)   Category
NewIndex
BA304_3_20x20             3    20x20          0.90  Angle_Bar
BA304_3_25x25             3    25x25          1.15  Angle_Bar
BA304_3_30x30             3    30x30          1.40  Angle_Bar
BA304_3_40x40             3    40x40          1.85  Angle_Bar
BA304_3_50x50             3    50x50          2.45  Angle_Bar
BA304_5_25x25             5    25x25          1.80  Angle_Bar
BA304_5_40x40             5    40x40          3.00  Angle_Bar
BA304_5_50x50             5    50x50          3.80  Angle_Bar
BA304_6_40x40             6    40x40          3.55  Angle_Bar
BA304_6_50x50             6    50x50          4.50  Angle_Bar
BA304_6_65x65             6    65x65          5.95  Angle_Bar
BA304_6_75x75             6    75x75          7.00  Angle_Bar
BA304_6_100x100           6  100x100          9.90  Angle_Bar
BA304_10_75x75           10    75x75         11.20  Angle_Bar
BA304_10_100x100         10  100x100         16.20  Angle_Bar

### Executing exactly the same for 'BA316'

In [44]:
BA316_index = []

for index, row in df_angleBar.iterrows():
    if row['BA316'] and row['Thickness'] and row['Size(mm)']:
        BA316_index.append(f"BA316_{row['Thickness']}_{row['Size(mm)']}")
    else:
        BA316_index.append(None)

df_angleBar['NewIndex'] = BA316_index
df_316 = df_angleBar[['NewIndex','Thickness','Size(mm)','Weight(kg/m)']]
df_316 = df_316.dropna().set_index('NewIndex')#Dropping null values and inserting the new index.
df_316['Category'] = 'Angle_Bar' #Adding the category "Angle_Bar to the table".
df_316.to_excel('./Resources/angleBar316Index.xlsx')

In [45]:
#This is the result of the new 316 index Angle_Bar table.
df_316

                  Thickness Size(mm)  Weight(kg/m)   Category
NewIndex
BA316_3_20x20             3    20x20          0.90  Angle_Bar
BA316_3_25x25             3    25x25          1.15  Angle_Bar
BA316_3_30x30             3    30x30          1.40  Angle_Bar
BA316_3_40x40             3    40x40          1.85  Angle_Bar
BA316_3_50x50             3    50x50          2.45  Angle_Bar
BA316_5_25x25             5    25x25          1.80  Angle_Bar
BA316_5_30x30             5    30x30          2.20  Angle_Bar
BA316_5_40x40             5    40x40          3.00  Angle_Bar
BA316_5_50x50             5    50x50          3.80  Angle_Bar
BA316_6_25x25             6    25x25          2.20  Angle_Bar
BA316_6_30x30             6    30x30          2.90  Angle_Bar
BA316_6_40x40             6    40x40          3.55  Angle_Bar
BA316_6_50x50             6    50x50          4.50  Angle_Bar
BA316_6_65x65             6    65x65          5.95  Angle_Bar
BA316_6_75x75             6    75x75          7.00  Angle_Bar
BA316_6_100x100           6  100x100          9.90  Angle_Bar
BA316_8_50x50             8    50x50          6.00  Angle_Bar
BA316_8_65x65             8    65x65          7.87  Angle_Bar
BA316_8_75x75             8    75x75          9.30  Angle_Bar
BA316_10_50x50           10    50x50          7.50  Angle_Bar
BA316_10_75x75           10    75x75         11.20  Angle_Bar
BA316_10_100x100         10  100x100         16.20  Angle_Bar
BA316_10_150x150         10  150x150         23.67  Angle_Bar
BA316_12_100x100         12  100x100         17.67  Angle_Bar